### PR TITLE
Homework 3 

### PR DESCRIPTION
**Pull request by rohan-singh1**
1. Exercise 01 - Node.js Routing Exercise
2. Exercise 02 - Node.js URL Exercise
3. Exercise 03 - Form Exercise

### CODE REVIEW

**Comment by mahlpdx** [comment]
Great job Rohan!

We took very similar approaches to these exercises. 

With exercise 1, I was quite impressed with your /check-cookies implementation -- the iteration through all cookies and reassignment of message "no" to "yes" is quite robust. 

On exercise 2, your code is really concise. There are no unused variables or unnecessary statements. 

For exercise 3, I like your use of case statements to separate the different paths. The only suggestion I have here is to move `let form_html_string` to the beginning of the document, since it is referenced before it is defined.

**Comment by rohan-singh1** [comment]
> Great job Rohan!
> 
> We took very similar approaches to these exercises.
> 
> With exercise 1, I was quite impressed with your /check-cookies implementation -- the iteration through all cookies and reassignment of message "no" to "yes" is quite robust.
> 
> On exercise 2, your code is really concise. There are no unused variables or unnecessary statements.
> 
> For exercise 3, I like your use of case statements to separate the different paths. The only suggestion I have here is to move `let form_html_string` to the beginning of the document, since it is referenced before it is defined.

Fixed. Thanks man! @mahlpdx

**Review by Al1999 — APPROVED** [review]
Hi Rohan,

For exc#1, your code looks organized and clean. I like how implemented check-cookies URL. 

For exc#2, you made this code looks simple and clean. I never thought of using includes as it would make my code a lot simpler haha! but good job!

For exc#3, using _switch_ instead of _'else if'_  made your code more compelling to look at.  Also, good job using _URLSearchParams_ . I think I need to do more reading about this feature. 

Overall you have done an incredible job in this assignment 

Thank you for sharing!
Al

**Comment by SwaroopaSK** [comment]
Hi Rohan,

Your code looks very neat and you have minimized the code so well in exercise 2. And it is easy to understand.

**Pull request merged**
