### PR TITLE
Code for FizzBuzz program added

### PR DESCRIPTION
**Pull request by rohan-singh1**

### CODE REVIEW

**Comment by KSKRLIFE** [comment]
Hi Rohan,

Looks like you forgot to call the function fizzbuzz() at the end.

**Comment by rohan-singh1** [comment]
@KSKRLIFE Hi Kishore, the function fizzbuzz is already there; it's on line #33. Github just collapsed it because no changes were made.

Screenshot 2022-10-05 at 4 13 05 PM

**Comment by KSKRLIFE** [comment]
> @KSKRLIFE Hi Kishore, the function fizzbuzz is already there; it's on line #33. Github just collapsed it because no changes were made.
> 
> Screenshot 2022-10-05 at 4 13 05 PM

Got you. It looks perfect.

**Comment by mahlpdx** [comment]
Hey Rohan,

The code looks good! One thing you can change is replacing your for loop with a higher-order function. This will help align your code more closely with the airbnb style guide: https://github.com/airbnb/javascript#iterators-and-generators

**Comment by rohan-singh1** [comment]
@mahlpdx Thanks for the tip Drew! I've bookmarked the link.

**Review by Al1999 — COMMENTED** [review]
Hi Rohan,

Your code looks good. I like how you coded the condition if it is divided by 3 and 5. I cannot see many issues in your code. Great job overall :)

Al

**Comment by SwaroopaSK** [comment]
Hi Rohan, The code looks good and the usage of if condition to check the divisibility is good.

**Pull request merged**
